



// MAINTENANCES
export const FETCH_MAINTENANCES_REQUEST = "FETCH_MAINTENANCES_REQUEST";
export const FETCH_MAINTENANCES_SUCCESS = "FETCH_MAINTENANCES_SUCCESS";
export const FETCH_MAINTENANCES_SUCCESS_2 = "FETCH_MAINTENANCES_SUCCESS_2";
export const FETCH_MAINTENANCES_FAILURE = "FETCH_MAINTENANCES_FAILURE";
// MAINTENANCES LOADING
export const FETCH_MAINTENANCE_REQUEST = "FETCH_MAINTENANCE_REQUEST";
export const FETCH_MAINTENANCE_SUCCESS = "FETCH_MAINTENANCE_SUCCESS";
export const FETCH_MAINTENANCE_FAILURE = "FETCH_MAINTENANCE_FAILURE";


// administrateurs
export const FETCH_ADMINS_REQUEST = "FETCH_ADMINS_REQUEST";
export const FETCH_ADMINS_SUCCESS = "FETCH_ADMINS_SUCCESS";
export const FETCH_ADMINS_SUCCESS_2 = "FETCH_ADMINS_SUCCESS_2";
export const FETCH_ADMINS_FAILURE = "FETCH_ADMINS_FAILURE";
// ADMINS LOADING
export const FETCH_ADMIN_REQUEST = "FETCH_ADMIN_REQUEST";
export const FETCH_ADMIN_SUCCESS = "FETCH_ADMIN_SUCCESS";
export const FETCH_ADMIN_FAILURE = "FETCH_ADMIN_FAILURE";



// utilisateurs
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_SUCCESS_2 = "FETCH_USERS_SUCCESS_2";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
// USERS LOADING
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";


// Agenda
export const FETCH_AGENDAS_REQUEST = "FETCH_AGENDAS_REQUEST";
export const FETCH_AGENDAS_SUCCESS = "FETCH_AGENDAS_SUCCESS";
export const FETCH_AGENDAS_SUCCESS_2 = "FETCH_AGENDAS_SUCCESS_2";
export const FETCH_AGENDAS_SUCCESS_D = "FETCH_AGENDAS_SUCCESS_D";
export const FETCH_AGENDAS_FAILURE = "FETCH_AGENDAS_FAILURE";
// AGENDAS LOADING
export const FETCH_AGENDA_REQUEST = "FETCH_AGENDA_REQUEST";
export const FETCH_AGENDA_SUCCESS = "FETCH_AGENDA_SUCCESS";
export const FETCH_AGENDA_FAILURE = "FETCH_AGENDA_FAILURE";







// Trajet 
export const FETCH_TRIPS_REQUEST = "FETCH_TRIPS_REQUEST";
export const FETCH_TRIPS_SUCCESS = "FETCH_TRIPS_SUCCESS";
export const FETCH_TRIPS_SUCCESS_2 = "FETCH_TRIPS_SUCCESS_2";
export const FETCH_TRIPS_SUCCESS_D = "FETCH_TRIPS_SUCCESS_D";
export const FETCH_TRIPS_FAILURE = "FETCH_TRIPS_FAILURE";
// TRIPS LOADING
export const FETCH_TRIP_REQUEST = "FETCH_TRIP_REQUEST";
export const FETCH_TRIP_SUCCESS = "FETCH_TRIP_SUCCESS";
export const FETCH_TRIP_FAILURE = "FETCH_TRIP_FAILURE";






// notification 
export const FETCH_NOTIFICATIONS_REQUEST = "FETCH_NOTIFICATIONS_REQUEST";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_SUCCESS_2 = "FETCH_NOTIFICATIONS_SUCCESS_2";
export const FETCH_NOTIFICATIONS_SUCCESS_D = "FETCH_NOTIFICATIONS_SUCCESS_D";
export const FETCH_NOTIFICATIONS_FAILURE = "FETCH_NOTIFICATIONS_FAILURE";
// NOTIFICATIONS LOADING
export const FETCH_NOTIFICATION_REQUEST = "FETCH_NOTIFICATION_REQUEST";
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_SUCCESS";
export const FETCH_NOTIFICATION_FAILURE = "FETCH_NOTIFICATION_FAILURE";



// Parkings 
export const FETCH_PARKINGS_REQUEST = "FETCH_PARKINGS_REQUEST";
export const FETCH_PARKINGS_SUCCESS = "FETCH_PARKINGS_SUCCESS";
export const FETCH_PARKINGS_SUCCESS_2 = "FETCH_PARKINGS_SUCCESS_2";
export const FETCH_PARKINGS_SUCCESS_D = "FETCH_PARKINGS_SUCCESS_D";
export const FETCH_PARKINGS_FAILURE = "FETCH_PARKINGS_FAILURE";
// PARKINGS LOADING
export const FETCH_PARKING_REQUEST = "FETCH_PARKING_REQUEST";
export const FETCH_PARKING_SUCCESS = "FETCH_PARKING_SUCCESS";
export const FETCH_PARKING_FAILURE = "FETCH_PARKING_FAILURE";



// Category
export const FETCH_CATEGORYS_REQUEST = "FETCH_CATEGORYS_REQUEST";
export const FETCH_CATEGORYS_SUCCESS = "FETCH_CATEGORYS_SUCCESS";
export const FETCH_CATEGORYS_SUCCESS_2 = "FETCH_CATEGORYS_SUCCESS_2";
export const FETCH_CATEGORYS_SUCCESS_D = "FETCH_CATEGORYS_SUCCESS_D";
export const FETCH_CATEGORYS_FAILURE = "FETCH_CATEGORYS_FAILURE";
// CATEGORYS LOADING
export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";



// Regions
export const FETCH_REGIONS_REQUEST = "FETCH_REGIONS_REQUEST";
export const FETCH_REGIONS_SUCCESS = "FETCH_REGIONS_SUCCESS";
export const FETCH_REGIONS_SUCCESS_2 = "FETCH_REGIONS_SUCCESS_2";
export const FETCH_REGIONS_SUCCESS_D = "FETCH_REGIONS_SUCCESS_D";
export const FETCH_REGIONS_FAILURE = "FETCH_REGIONS_FAILURE";
// REGIONS LOADING
export const FETCH_REGION_REQUEST = "FETCH_REGION_REQUEST";
export const FETCH_REGION_SUCCESS = "FETCH_REGION_SUCCESS";
export const FETCH_REGION_FAILURE = "FETCH_REGION_FAILURE";




//Ppublication
export const FETCH_PUBLICATIONS_REQUEST = "FETCH_PUBLICATIONS_REQUEST";
export const FETCH_PUBLICATIONS_SUCCESS = "FETCH_PUBLICATIONS_SUCCESS";
export const FETCH_PUBLICATIONS_SUCCESS_2 = "FETCH_PUBLICATIONS_SUCCESS_2";
export const FETCH_PUBLICATIONS_SUCCESS_D = "FETCH_PUBLICATIONS_SUCCESS_D";
export const FETCH_PUBLICATIONS_FAILURE = "FETCH_PUBLICATIONS_FAILURE";
// PUBLICATIONS LOADING
export const FETCH_PUBLICATION_REQUEST = "FETCH_PUBLICATION_REQUEST";
export const FETCH_PUBLICATION_SUCCESS = "FETCH_PUBLICATION_SUCCESS";
export const FETCH_PUBLICATION_FAILURE = "FETCH_PUBLICATION_FAILURE";







// code postals 
export const FETCH_CODE_POSTALS_REQUEST = "FETCH_CODE_POSTALS_REQUEST";
export const FETCH_CODE_POSTALS_SUCCESS = "FETCH_CODE_POSTALS_SUCCESS";
export const FETCH_CODE_POSTALS_SUCCESS_2 = "FETCH_CODE_POSTALS_SUCCESS_2";
export const FETCH_CODE_POSTALS_SUCCESS_D = "FETCH_CODE_POSTALS_SUCCESS_D";
export const FETCH_CODE_POSTALS_FAILURE = "FETCH_CODE_POSTALS_FAILURE";
// CODE_POSTALS LOADING
export const FETCH_CODE_POSTAL_REQUEST = "FETCH_CODE_POSTAL_REQUEST";
export const FETCH_CODE_POSTAL_SUCCESS = "FETCH_CODE_POSTAL_SUCCESS";
export const FETCH_CODE_POSTAL_FAILURE = "FETCH_CODE_POSTAL_FAILURE";







// Messages sms
export const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_SUCCESS_2 = "FETCH_MESSAGES_SUCCESS_2";
export const FETCH_MESSAGES_SUCCESS_D = "FETCH_MESSAGES_SUCCESS_D";
export const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE";
// MESSAGES LOADING
export const FETCH_MESSAGE_REQUEST = "FETCH_MESSAGE_REQUEST";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_FAILURE = "FETCH_MESSAGE_FAILURE";





// Chargement des boutiques
// conversations
export const FETCH_CONVERSATIONS_SUCCESS = "FETCH_CONVERSATIONS_SUCCESS";
export const FETCH_CONVERSATIONS_SUCCESS_2 = "FETCH_CONVERSATIONS_SUCCESS_2";
export const FETCH_CONVERSATIONS_SUCCESS_FILTER = "FETCH_CONVERSATIONS_SUCCESS_FILTER";
export const FETCH_CONVERSATIONS_SUCCESS_FILTER_2 = "FETCH_CONVERSATIONS_SUCCESS_FILTER_2";
// participants
export const FETCH_PARTICIPANTS_SUCCESS = "FETCH_PARTICIPANTS_SUCCESS";
export const FETCH_PARTICIPANTS_SUCCESS_2 = "FETCH_PARTICIPANTS_SUCCESS_2";
export const FETCH_PARTICIPANTS_SUCCESS_FILTER = "FETCH_PARTICIPANTS_SUCCESS_FILTER";
export const FETCH_PARTICIPANTS_SUCCESS_FILTER_2 = "FETCH_PARTICIPANTS_SUCCESS_FILTER_2";

export const FETCH_CONVERSATIONS_SEND = "FETCH_CONVERSATIONS_SEND";
export const FETCH_CONVERSATIONS_FAILURE = "FETCH_CONVERSATIONS_FAILURE"
//      chargement
export const SEND_REQUEST_CONVERSATION = "SEND_REQUEST_CONVERSATION";
export const REQUEST_SUCCESS_CONVERSATION = "REQUEST_SUCCESS_CONVERSATION";
export const REQUEST_FAILURE_CONVERSATION = "REQUEST_FAILURE_CONVERSATION";
// select
export const SELECT_USER_CONVERSATION = "SELECT_USER_CONVERSATION";















// TRADUCTION DE LA LANGUE ;
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const changeLanguage = (language) => ({
  type: CHANGE_LANGUAGE,
  payload: language,
});